name: hive_mirror
description: One way sync for hive databases.
version: 0.1.0
author: Guillaume Ducret
homepage: https://github.com/GuillaumeDucret/hive_mirror

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.4.2
  collection: ^1.15.0
  hive: ^2.0.0

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.4
  build_runner: ^1.12.2
