name: hive_mirror
description: One way sync for hive databases.
version: 0.0.1
author: Guillaume Ducret
homepage: https://github.com/GuillaumeDucret/hive_mirror

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  async: ^2.4.2
  isolate: ^2.0.3
  hive: ^1.4.4

dev_dependencies:
  test: ^1.15.4
  mockito: ^4.1.3
